### ISSUE TITLE
Knowledge sharing

### ISSUE THREAD

**Issue by Sgambe33** [Yay5379/wt_client_replay_parser#1]
Hi, I saw that you are interested in replays and kinda know more about them looking at the issues on wt-tools repository. I was wondering if you would like to collaborate to try and extract more data from these files. Thx.

**Comment by Yay5379** [comment]
I would love to collaborate. As far as client replays go most of the remaining information is related to packets and stuff like that and the code in this repository will parse everything that is know so far.

**Comment by Sgambe33** [comment]
> I would love to collaborate. As far as client replays go most of the remaining information is related to packets and stuff like that and the code in this repository will parse everything that is know so far.

Awesome! You can dm me on discord: sgambe_
